Feat/home screen baca
binarapps/baca-react-native-template pull request #65
Opened 2024-06-19 12:04 UTC by olafch

# Description

I've added a new header, subtitle, the two buttons that are present in Docusaurus, and the slider to the website. I've made all the elements responsive. I merged the main branch because I thought I could reuse code from docs (but that was not the case)

## Type of change
- [x] New feature (non-breaking change which adds functionality)

2024-06-20 08:49 UTC, MateuszRostkowski commented on src/screens/HomeScreen.tsx
This changes should be applied to `LandingScreen` not `HomeScreen` :D

2024-06-20 08:50 UTC, MateuszRostkowski commented on src/screens/HomeScreen.web.tsx
> +        justifyContent={'center'}
It don't have any impact on code you can change all this props like this:

```suggestion
        justifyContent="center"
```

2024-06-20 08:52 UTC, MateuszRostkowski commented on src/screens/index.ts
> +export * from '../screens/drafts/images'
```suggestion
export * from './drafts/images'
```

2024-06-21 08:21 UTC, olafch commented on src/screens/HomeScreen.tsx
Makes sense, thank you Mateusz!

2024-06-24 07:43 UTC, MateuszRostkowski requested changes
One little improvment to add, and it is ready to merge! :D 🚀

2024-06-24 07:43 UTC, MateuszRostkowski commented on src/screens/LandingScreen.tsx
> +  useScreenOptions({ title: t('navigation.screen_titles.home') })
You have this hook used two times. Just remove this one.

2024-06-28 11:01 UTC, merged